[package]
name = "workspace-alias"
version = "0.1.0"
edition = "2021"

[dependencies]
colorful = "0.2.2"
regex = "1.10.4"
reqwest = "0.11.24"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
